* 添加个人中心网络库模块

* body的数据如何传进去http模块进行route_packet()
*  CGuiHttpClient::route_packet()
   这个模块基本就是进行xml和json格式的生成。
   现在要跟踪的就是生成需要格式的数据来源是从那里来？
**   方法一：
     看看旧的xml问题，和相关模块网络命令的调用，就可以得知数据来的来源。
**   方法二：
     可以猜测数据应该是由应用层来进行数据的传输，从应用层来跟踪到网络层，结合uml图来进行理解。
     看看是不是c++一些特性 ，不能象c一样进行一步步的跟踪，抽象了一定的代码。

* data_service () 每个模块都有相应的data_service（）这个函数。
  估计就是这个函数来进行把数据转换为xml格式----> CGuiServiceBase() 中odata_service()这个函数就是纯虚函数。
  父类会
  
* 发送获取兑换率的json信息

  {
  "Own":"aaa",//运营商 //xqq帮我们加
  "Version":"1.0.0",
  "ServiceCode":"Rates",
  "Requestid":"2014010200000001",//流水号
  "RequestContent":
  {"Type":1} //类型 1：为RMB转T币， 2: T币兑换T卷
  }

** 问题一：
   运营商的信息如何获取到？ xqq帮忙加上去
** 问题二
   数据发送出去，那里接收？
   数据是分段接收的，所以在判断大小长度之后，就只用memmove进行数据的偏移。

 * 在跟服务器通讯这个模块里面，单单接收和发送问题不大，
   在做不同数据的包里面，就显现出一种需求，文件发送的格式可能发生了变化。应该如何抽象出来。
** 问题三
   如何设计一个类来保存相关的个人信息


* 汇率的接收的json数据的解析
  {"RequestID":null,
  "ServiceCode":"Rates",
  "Status":0,
  "Output":[{
  "Start":0,//充值0到49的范围
  "End":49,
  "Rate":100,//汇率是一块钱兑换100个T币
  "Handsel":0//表示赠送为0
  },
  {"Start":49,//特定范围呃
  "End":50,
  "Rate":100,
  "Handsel":500 //赠送500个T币
  },
  {"Start":50,
  "End":999999999,
  "Rate":109,//汇率变化高了
  "Handsel":0
  }]
  }



* parse_packet解析接收的数据？
** 问题一：
   在那里解析数据和保存数据
** 问题二：
   数据在那里删除？



   





























































* 专注力
** 从大脑的结构来看
   出现小差的情况，一般可能是门槛的兴奋度不够，或者是其他的因素来影响了大脑，比如声音，或者一些动作。
   这个时候，可以转移一下大脑的抗拒的程度，深呼吸之类的放松，能充分放松，平常心才可以有更好的工作效率。
   
* 事件的积累
  做任何事情，都一样。都是从小的开始积累。
  代码的打印，一时图个方便，printf直接打印。一个小时后，改printf都可以改得吐血。

  